# Generated by Django 4.1.7 on 2023-02-24 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='url',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
